name: Sonic Nexus 3DS Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Sonic Nexus 3DS Build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build
      - name: Download and install dependencies
        run : |
          apt install build-essential 
          apt install git 
          apt install libsdl2-dev 
          apt install libvorbis-dev 
          apt install libogg-dev 
          apt install libtheora-dev       
      - name: Build Sonic Nexus for the Nintendo 3DS
        run: make