name: Build (Nintendo 3DS)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  n3ds:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build
          apt install unzip
      - name: Download libogg, libvorbis, and libtheora for easier includes
        run : |
          wget https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.zip -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/linux/
          Rename-Item ./dependencies/linux/libogg-1.3.5 libogg
          wget https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/linux/
          Rename-Item ./dependencies/linux/libvorbis-1.3.7 libvorbis
      - name: Download SDL2
        run: |
          wget https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/linux/
          Rename-Item ./dependencies/linux/SDL2-2.0.14 SDL2
      - name: Run vcpkg
        run: |
          vcpkg install libogg:x86-windows-static libvorbis:x86-windows-static libtheora:x86-windows-static
          vcpkg integrate install          
      - name: Build
        run: make